swagger: "2.0"
info:
  title: Hello Service
  description: A hello world service.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /hello/{name}:
    get:
      tags:
      - hello
      summary: hello hello
      operationId: hello#hello
      parameters:
      - name: name
        in: path
        description: name
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - hello
      summary: Download ./gen/http/openapi.json
      operationId: hello#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
